### ISSUE TITLE
Add rich graphics to your SwiftUI app

### ISSUE THREAD

**Issue by HoJongPARK** [WWHigh/WWDC-STUDY#2]
### Safe Area 란?

- 아이폰 X 부터 등장한 개념으로, 이전 모델들과 다른 폼팩터와 홈버튼의 부재, 노치의 등장으로 나온 개념이다.

|아이폰 8|아이폰 X|
|:----------:|:----------:|
|<img src = "https://user-images.githubusercontent.com/57793298/170829242-72bb3d56-025e-4734-b3d1-712975878e00.png" height = 300>|<img src = "https://user-images.githubusercontent.com/57793298/170829267-9647a206-94a3-4fc8-9a61-438fc973783e.png" height = 300>|

- 아이폰 X 의 경우 홈 버튼의 역할을 화면 하단의 홈 인디케이터로 대체되었으므로, 인디케이터와 노치를 침범하지 않고 UI 를 배치하기 위해 **Safe Area** 라는 영역이 존재한다.
- 또한 키보드가 올라올 때를 대비하여 Keyboard Safe Area 도 존재한다.

|Container Safe Area|Keyboard not appear|Keyboard Safe Area|
|:---:|:---:|:---:|
|<img height="300" alt="image" src="https://user-images.githubusercontent.com/57793298/170829622-8b587c65-9079-42c7-b0bd-ffee3170d1d5.png">|<img height="300" alt="image" src="https://user-images.githubusercontent.com/57793298/170829915-54772b67-83cb-4a28-9855-c10149cd6a13.png">|<img height="300" alt="image" src="https://user-images.githubusercontent.com/57793298/170829925-d193ca9e-52a4-4f9d-ac2d-b93b2707fc6a.png">|

### Safe Area 무시하기

- 배경 이미지같이 Safe Area 를 무시하고 화면을 전부 차지해야 하는 컨텐츠의 경우 Safe Area 를 무시하는 것이 가능하다.

```swift
ZStack {
      Color.green
      // Safe area 를 무시하고 화면 영역을 차지한다.
        .ignoresSafeArea()
      Text("Hello World")
    }
```	

- 다음과 같이 특정 Safe Area 만 무시할 수도 있다.
```swift
ZStack {
      TextField("텍스트 필드", text: .constant("Keyboard Safe Area"))
        .font(.largeTitle)
        .padding()
    }
    .frame(maxWidth: .infinity, maxHeight: .infinity)
    .border(.green, width: 2)
    // Keyboard Safe Area 만 무시한다.
    .ignoresSafeArea(.keyboard)
```

### Material 이란?

- Material 은 background modifier 에 적용할 수 있는 반투명한 배경이다.
- 단순한 반투명 배경이 아니며, 유리를 연상시키는 배경이다.
- 주로 색상이 있는 컨텐츠 위에 올라가는 UI 요소에서 활용할 수 있다.

<img src = "https://docs-assets.developer.apple.com/published/bb5a57048ddea75e0e2925b0d5a613da/Material-2~dark@2x.png" width = 400>

```swift
ZStack {
      LinearGradient(colors: [.blue, .yellow, .red], startPoint: .topLeading, endPoint: .bottomTrailing)
        .ignoresSafeArea(.container)
      Label("Hello World", systemImage: "hand.raised")
        .padding()
        .background(.thinMaterial, in: RoundedRectangle(cornerRadius: 20))
    }
```
<img width="200" alt="image" src="https://user-images.githubusercontent.com/57793298/170846962-c1627a1d-f02b-475e-8247-98305599cd62.png">

- 다음과 같이 6가지의 Material 이 존재하며, 다크 모드와 라이트 모드에서 서로 다르게 표현된다.
<img src = "https://docs-assets.developer.apple.com/published/c05b1d346013946445ae5f3c5b56541f/Material-4~dark@2x.png" width = 300>

### Foreground Style 이란?

- **foreground UI elements 의 색을 채울 때 사용할 색상이나 패턴 등을 의미한다.**

### Color Foreground Style
```swift
HStack {
      Image(systemName: "hand.raised")
      Text("Hello World")
    }
    .foregroundStyle(.teal)
```
<img width="240" alt="image" src="https://user-images.githubusercontent.com/57793298/170847603-ca38148b-cb84-4c2c-9a6f-385a6d244e0f.png">

### Gradient Foreground Style
```swift
HStack {
      Image(systemName: "hand.raised")
        .imageScale(.large)
      Text("Hello World")
        .font(.largeTitle)
    }
    .foregroundStyle(.linearGradient(colors: [.green, .blue], startPoint: .top, endPoint: .bottom))
```
<img width="240" alt="image" src="https://user-images.githubusercontent.com/57793298/170847647-59fd9af9-0c16-445a-8197-f74194159559.png">

### Hierarchical foreground style
- 계층 구조에서 가장 가까운 부모에서 선언된 foregroundStyle 을 사용해, 자기의 계층에 맞게 해당 기본 스타일을 변경한다.
```swift
VStack {
      Text("Primary")
// primary 계층
        .foregroundStyle(.primary)
      Text("Secondary")
// secondary 계층
        .foregroundStyle(.secondary)
      Text("Tertiary")
// tertiary 계층
        .foregroundStyle(.tertiary)
      Text("Quatenary")
// quaternary 계층
        .foregroundStyle(.quaternary)
    }
    .font(.largeTitle)
    .foregroundStyle(.linearGradient(colors: [.green, .blue], startPoint: .top, endPoint: .bottom))
```
<img width="240" alt="image" src="https://user-images.githubusercontent.com/57793298/170847761-a503751e-6d5c-4316-9c37-a3244acf3f12.png">

- 가장 가까운 부모인 VStack 에 적용된 foregroundStyle 을 기반으로, 각 Text 에 hierarchical style 이 적용된 모습을 볼 수 있다.

## Safe Area Inset View Modifier

- 커스텀 Safe Area 를 생성할 수 있는 Modifier
```swift
func safeAreaInset<V>(edge: HorizontalEdge, alignment: VerticalAlignment = .center, spacing: CGFloat? = nil, content: () -> V) -> some View where V : View
```

- **edge**: content 의 크기에 따라 안전 영역을 생성할 가장자리
- **spacing**: Safe area content 와 Modifier 가 적용될 View 와의 여백을 나타낸다
- **content**: ViewBuilder function 으로, 사용자가 지정한 가장자리의 inset 에 content 를 그린다.

### 예시

- 다음과 같은 View 가 있다. Material 을 적용한 UI 요소가 화면 아래 부분에 배치된 UI 로, 스크롤을 끝까지 하면 Mint 색상의 Rectangle 과 bottom Text가 겹치는 것을 확인할 수 있다.

```swift
let colors: [Color] = [.red, .green, .blue, .cyan, .orange, .yellow, .purple, .indigo, .brown, .pink, .mint]

ZStack(alignment: .bottom) {
      ScrollView(.vertical, showsIndicators: false) {
        VStack(spacing: 0) {
          ForEach(colors, id: \.self) { color in
            Rectangle().fill(color).frame(height: 150)
          }
        }
      }
      Text("Bottom Safe Area Inset")
        .frame(width: UIScreen.main.bounds.width)
        .padding()
        .background(.regularMaterial)
    }
```

<img width="291" alt="image" src="https://user-images.githubusercontent.com/57793298/170848602-6283b7d4-1e6e-4b94-a4a1-05c63fe83a44.png">

- 위와 같이 Material 배경을 가지는 Text 가 아래에 배치되고, Rectangle 색상과 믹스되는 효과를 유지하면서 ScrollView 가 실질적으로 차지하는 영역을 Text 를 침범하지 않게 만들기 위해, Bottom Safe Area Inset 을 사용할 수 있다.

```swift
    ScrollView(.vertical, showsIndicators: false) {
      VStack(spacing: 0) {
        ForEach(colors, id: \.self) { color in
          Rectangle().fill(color).frame(height: 150)
        }
      }
    }
// bottom 가장자리에 사용자 정의 content 가 그려질 safe area inset 을 생성!
    .safeAreaInset(edge: .bottom, spacing: 0) {
      Text("Bottom Safe Area Inset")
        .frame(width: UIScreen.main.bounds.width)
        .padding()
        .background(.regularMaterial)
    }
```

<img width="240" alt="image" src="https://user-images.githubusercontent.com/57793298/170848681-f5fb5f19-df6c-4bb6-853c-a9d3bb5c90b6.png">

- ScrollView 의 마지막 요소인 Mint 색상의 Rectangle 도 화면에 정상적으로 표시되는 것을 확인할 수 있다.

**Comment by wody-d** [comment]
제가 알기론 내용이 더 있는 걸로 아는데요?  😿 ㅋㅋㅋ

**Comment by HoJongPARK** [comment]
> 제가 알기론 내용이 더 있는 걸로 아는데요? 😿 ㅋㅋㅋ

있는데 없습니다
