### ISSUE TITLE
What`s new in Xcode

### ISSUE THREAD

**Issue by HoJongPARK** [WWHigh/WWDC-STUDY#23]
## What`s new in xcode

macOS Ventura 가 나오면서 Xcode 도 새로운 버전이 나왔습니다. 새로운 버전에선 Xcode 의 성능이 향상되고, 또한 개발자의 생산성을 올려줄 많은 기능이 추가되었습니다.

### SwiftUI Preview

- 이제 SwiftUI 프리뷰는 기본적으로 interactive 합니다.
- 따로 프리뷰를 작성하지 않아도, 프리뷰에 다양한 변화를 줄 수 있습니다.

### color scheme variant
- color scheme variant 로 라이트 모드와 다크 모드 프리뷰를 동시에 볼 수 있습니다.

<img width="226" alt="image" src="https://user-images.githubusercontent.com/57793298/177535735-36891433-b4e4-4e02-8717-419ee7e312c2.png">
<img width="743" alt="image" src="https://user-images.githubusercontent.com/57793298/177535945-20cac9cc-4243-46be-8a5e-acc734392021.png">

### orientation variant
- orientation variant 로 portrait, landscape 화면의 프리뷰를 동시에 볼 수 있습니다
<img width="723" alt="image" src="https://user-images.githubusercontent.com/57793298/177536163-bcff859a-735b-42aa-b168-2f70cc8b122c.png">

### dynamic type variant
- dynamic type variant 로 다양한 시스템 폰트 크기의 프리뷰를 동시에 볼 수 있습니다
<img width="753" alt="image" src="https://user-images.githubusercontent.com/57793298/177536345-5fe8ab29-8f5c-4e68-b5d6-bfb8d9cb2bd0.png">

### Editor
- 이제 initializer 를 작성할 때 모든 프로퍼티가 포함된 initializer 를 자동완성으로 추천해줍니다.
<img width="429" alt="image" src="https://user-images.githubusercontent.com/57793298/177536928-f1b37348-b52c-458c-a79a-2ff8b3abfc23.png">

- initializer 자동완성을 선택하면, 다음과 같이 프로퍼티 초기화 코드까지 함께 작성됩니다.

<img width="373" alt="image" src="https://user-images.githubusercontent.com/57793298/177546852-558e2ed1-c0c8-4753-af70-a063516c8633.png">

- default Value 가 있는 initializer 는, 다음 사진과 같이 자동완성으로 추천됩니다.
<img width="426" alt="image" src="https://user-images.githubusercontent.com/57793298/177547090-05ba99bd-c023-4c7a-8a06-41d1f071347a.png">
<img width="497" alt="image" src="https://user-images.githubusercontent.com/57793298/177547204-250cf7aa-e3b9-4958-becf-7957bfe311e3.png">

- 이제 에디터 상단에 항상 현재 코드의 definition 이 보입니다. 

<img width="764" alt="image" src="https://user-images.githubusercontent.com/57793298/177549127-baeae4f5-e0d6-4a76-af83-95d1c0c23178.png">

### Definition

- 이제 프로토콜 함수 호출 코드에서 definition 을 클릭하면, 해당 프로토콜을 구현한 모든 타입 목록이 리스트에 등장합니다.
<img width="526" alt="image" src="https://user-images.githubusercontent.com/57793298/177548296-5a65328a-ef44-4660-8e37-7f3de4910f5a.png"> 

### Performance

- 25% 빨라진 빌드 
- 30% 빨라진 테스트 실행 속도
- 50% 빨라진 Interface Builder document 로딩 속도
- 30% 빨라진 Preview Device switching 속도

**Comment by chaneeii** [comment]
+ 조금 더 이뻐진 UI 🥳
