### ISSUE TITLE
Craft search experiences in SwiftUI

### ISSUE THREAD

**Issue by Chaeho-Min** [WWHigh/WWDC-STUDY#5]
iOS의 네이티브 검색 기능은 3가지로 이루어져 있습니다.

|검색바|검색 제안|검색 결과|
|:---:|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/75792767/172051232-63c20774-5532-4598-981a-4deec2a45d04.png" />|<img width="250" src="https://user-images.githubusercontent.com/75792767/172051232-63c20774-5532-4598-981a-4deec2a45d04.png"/>|<img width="250" src="https://user-images.githubusercontent.com/75792767/172051534-818be765-544f-48e9-8719-ce75f67edf24.png"/>|

iOS15에서 .searchable 수식어의 등장으로, 이제 SwiftUI에서 네이티브 검색 기능을 구현할 수 있게 됐습니다.
<br/>
## .searchable

.searchable 수식어는 말 그대로 내비게이션바에 검색바를 추가하여 검색 가능(search + able)하게 만들어줍니다.

<img width="250" src="https://user-images.githubusercontent.com/75792767/172051929-99efa181-e330-4b99-a511-c7f64ad19034.png" />

```swift
NavigationView {
    WeatherList()
}
.searchable(text: $text)
```

검색바는 텍스트를 입력 받기 때문에 바인딩값을 매개변수로 줘야 합니다.
</br>
### 검색바 위치
iPad에서는 수식어의 위치에 따라 검색바의 위치가 변합니다.
<br/>
![주식어플](https://user-images.githubusercontent.com/75792767/172052036-cb76d303-cb25-4770-b0cc-f168b5611e2d.png)
```swift
NavigationView {
    Sidebar()
    DetailView()
}
.searchable(text: $text)
```
아이패드에서 searchable 수식어는 기본적으로 사이드바에 검색바를 생성합니다.
<br/>
![메모어플](https://user-images.githubusercontent.com/75792767/172052073-f92d3156-dafd-43e3-9233-05764d1170f9.png)
```swift
NavigationView {
    Sidebar()
    DetailView()
        .searchable(text: $text)
}
```
디테일뷰에 검색바를 두고 싶다면, searchable 수식어가 디테일뷰를 수식하게 하면 됩니다.
<br/>
## Search Results

검색 기능이 동작하게 하려면 검색 결과를 나타내는 뷰를 구현해야 합니다.
|검색 결과가 있을 때|검색 결과가 없을 때|
|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/75792767/172052233-1501f0ae-f3c4-4b6a-bfa3-64c5b7fc872b.png" />|<img width="250" src="https://user-images.githubusercontent.com/75792767/172052255-764ca8e6-d6d7-400e-9854-54a9b19b0b3a.png" />|

```swift
@Environment(\.isSearcing) private var isSearching: Bool

var body: some View {
    WeatherCitiesList()
        .overlay {
            if isSearching && !text.isEmpty {
                SearchResults()
            }
        }
}
```

> ”consider using overlay so that the state of your main UI is unchanged after a user returns from their search interaction.”
> 

WWDC 영상에서는 검색 결과 뷰를 overlay 수식어로 나타내는 것을 추천했습니다. 그 이유는 overlay를 사용하면 사용자가 검색을 취소하고 돌아왔을 때 이전의 상태를 그대로 보여줄 수 있기 때문입니다.

예를 들어 스크롤뷰에서 스크롤을 어느 정도 내린 후에 검색 기능으로 검색을 하다가 취소 버튼을 눌렀을 때, 스크롤 위치가 이전 상태 그대로 유지되어야 사용자는 자연스러움을 느낄 것입니다.
<br/>
### \\.isSearching

```swift
@Environment(\.isSearching) private var isSearching: Bool
```

searchable 수식어를 갖고 있는 뷰의 자식뷰에서는 isSearching 환경변수를 통해 검색중인지 아닌지에 대한 정보를 얻을 수 있습니다.

<br/>

## Suggestions

![앱스토어검색제안](https://user-images.githubusercontent.com/75792767/172052376-4c1313bd-013d-4eff-bfa4-30269d15434f.png)

검색바만 있으면 사용자가 무엇을 검색해야 하는지 혼란스러워 할 수 있습니다. 이럴때 검색 제안 기능을 구현하여 검색에 도움을 줄 수 있습니다.
<br/>
```swift
public func searchable<S>(
    text: Binding<String>,
    placement: SearchFieldPlacement = .automatic,
    prompt: Text? = nil,
    @ViewBuilder suggestions: () -> S
) -> some View where S : View
```
searchable 수식어는 suggestions라는 뷰빌더 매개변수를 갖고 있습니다. 따라서 VStack처럼 중괄호 안에 뷰를 그리면 자동으로 검색 제안 뷰를 그려줍니다.
<br/>
```swift
.searchable(text: $text) {
		
    Button {
        text = "Youtube"
    } label: {
        Text("Youtube")
    }

    Button {
        text = "당근마켓"
    } label: {
        Text("당근마켓")
    }

    Button {
        text = "토스"
    } label: {
        Text("토스")
    }
}
```

suggestions 매개변수에 나열한 뷰는 자동으로 List로 나타납니다. 따라서 VStack에 넣을 필요가 없습니다.
<br/>
검색 제안은 보통 버튼의 형식으로, 클릭하면 검색바의 텍스트필드에 해당 키워드가 입력되게 됩니다. 이 기능을 매번 버튼으로 구현할 필요가 없도록, searchCompletion이라는 수식어를 제공합니다.
```swift
.searchable(text: $text) {
	
    Text("Youtube")
        .searchCompletion("Youtube")

    Text("당근마켓")
        .searchCompletion("당근마켓")

    Text("토스")
        .searchCompletion("토스")
}
```
searchCompletion 수식어는 뷰를 버튼으로 만들어주며, 매개변수로 받은 값을 검색바에 채워줍니다.
<br/>

<img width="250" src="https://user-images.githubusercontent.com/75792767/172052656-b08d7a4f-10de-4387-98e3-859f0a998c9c.png" />

suggestion 뷰는 키보드의 ‘검색'버튼을 눌러야 사라집니다.
<br/>
```swift
.searchable(text: $text) {
    searchSuggestions()
}
.onSubmit(of: .search) {
    viewModel.filteringData()
}
```
검색 버튼을 눌렀을 때 입력한 텍스트를 기반으로 데이터를 검색하는 메서드를 불러오고 싶다면, onSubmit 수식어에 .search를 전달하면 됩니다.
.search는 키보드의 검색 버튼을 눌렀을 때 트리거됩니다.
<br/>
```swift
func filteringData() {
    searchResults = data.filter { $0.contains(text) }
}
```
(데이터 검색 메서드 예시)

<br/>

### 검색바 placeholder
<img width="250" src="https://user-images.githubusercontent.com/75792767/172051929-99efa181-e330-4b99-a511-c7f64ad19034.png" />

```swift
.searchable(
    text: $text,
    prompt: "도시 또는 공항 검색"
)
```

.searchable의 prompt 매개변수를 이용하여 검색바의 placeholder를 변경할 수 있습니다.
<br/>

### 실시간 검색시 제안 화면

만약 ‘검색’ 버튼을 누르기 전에 검색 키워드의 일부만 입력했을 때도 실시간으로 검색 결과가 뜨게 하려면, 검색 제안 화면을 없애줘야 합니다.

if문을 사용하여 검색바에 입력한 텍스트가 없을 때만 제안 화면을 뜨게 하면 됩니다.

```swift
.searchable(text: $text) {
		
    if text.isEmpty {
        Text("Youtube")
            .searchCompletion("Youtube")

        Text("당근마켓")
            .searchCompletion("당근마켓")

        Text("토스")
            .searchCompletion("토스")
    }
}
```
<br/>

### ScrollView와 검색바

searchable 수식어가 ScrollView를 수식하게 되면 검색바는 자동으로 숨김 처리되고, 스크롤을 해야지만 나타나게 됩니다.

만약 ScrollView에서도 검색바가 계속 나타나 있게 하고 싶다면 placement 매개변수에 .navigationBarDrawer(displayMode: .always)를 전달해 주면 됩니다.

```swift
.searchable(
    text: $text,
    placement: .navigationBarDrawer(displayMode: .always)
)
```
<br/>

## Link
- [WWDC21 - Craft search experience in SwiftUI](https://developer.apple.com/wwdc21/10176)
- [searchable을 직접 적용해 본 코드](https://github.com/Chaeho-Min/ME_Mechanical-Engineering)
- [발표자료(키노트)](https://github.com/Chaeho-Min/ME_Mechanical-Engineering/blob/master/Searchable.key)
- [발표자료(PDF)](https://github.com/Chaeho-Min/ME_Mechanical-Engineering/blob/master/SearchablePDF.pdf)

**Comment by wody-d** [comment]
Craft...? 제목 뜻이 뭔가요?
